### PR TITLE
Implement wildfire protocol for max/min aggregation queries

### PR DESCRIPTION
**Pull request by fax4ever**
Hi, I played a bit with the project.
I tried to implement a WildFire protocol for aggregated distributed queries.
I found the algorithm here https://www.sciencedirect.com/science/article/pii/S0022000006001115?via%3Dihub
I don't know if I used correctly the framework. I tried to...

### CODE REVIEW

**Comment by fax4ever** [comment]
I made some fixes. Now the solution looks pretty stable to my tests.

**Comment by krzysztof-turowski** [comment]
Thank you very much - sorry for the late reply, but I'm a bit overloaded with other tasks, but I'll try to look into it in the near future!

**Comment by fax4ever** [comment]
> Thank you very much - sorry for the late reply, but I'm a bit overloaded with other tasks, but I'll try to look into it in the near future!

Hi @krzysztof-turowski, nice to meet you! No rush for it. Thanks!

**Comment by fax4ever** [comment]
Hi @krzysztof-turowski, I'm going to close this PR. Write me if you need I reopen it. Take care. Fabio

**Pull request closed without merging**
